# fly.toml app configuration file generated for orbitai
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "orbitai" # Name of your app on Fly.io
primary_region = "iad"  # Example region: Ashburn, VA. Choose one closer to your users: https://fly.io/docs/reference/regions/

[build]
  dockerfile = "Dockerfile" # Tells Fly to use the Dockerfile in your project root

[http_service]
  internal_port = 5001 # The port your app internally listens on (it uses process.env.PORT || 5001)
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Good for free tier; set to 1 for always-on (requires paid plan)
  processes = ["app"] # Default process group

# Optional: Define machine resources. Defaults are usually fine to start.
# [[vm]]
#   cpu_kind = "shared"
#   cpus = 1
#   memory_mb = 256 # Smallest available; monitor and increase if needed.
