# fly.toml app configuration file generated for orbit-api-bold-glitter-8422 on 2025-05-16T10:34:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbit-api-bold-glitter-8422'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[deploy]
  release_command = "npx prisma migrate deploy --schema=/app/prisma/schema.prisma"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    type = "tcp"
    port = 5001
    interval = "15s"
    timeout = "2s"
    grace_period = "7s"

  [[http_service.checks]]
    type = "http"
    port = 5001
    method = "GET"
    path = "/api/health" # Health check endpoint
    protocol = "http"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    tls_skip_verify = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
