# fly.toml app configuration file generated for orbit-api-bold-glitter-8422 on 2025-05-16T10:34:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbit-api-bold-glitter-8422'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[deploy]
  release_command = "npx prisma migrate deploy --schema=./prisma/schema.prisma"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
